// This file is automatically generated by the Firebase setup.
// Do not edit this file manually.
export const firebaseConfig = {
  "projectId": "peamellera-deps3-8230053-f44a5",
  "appId": "1:691560801127:web:47a1c0fd1e377bf1de05c2",
  "apiKey": "AIzaSyBnxoEfIDbJXucbnL-IJ9gNoM0SM4MP5wA",
  "authDomain": "peamellera-deps3-8230053-f44a5.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "691560801127"
};
